### ISSUE TITLE
Проблема с Permissions 

### ISSUE THREAD

**Issue by Fedor858** [developeruz/easyii-rbac-module#1]
Небольшая  проблема - 
Если мы в  админке  просто  открываем  модуль  то  все  нормально.
Если  переходим в   Update   То получаем такую картину 
![-2](https://cloud.githubusercontent.com/assets/18245402/22850738/66722c5c-f052-11e6-8562-10552c5d9bdf.png)
Такая  же ситуация и с Roles

**Comment by developeruz** [comment]
У автора EasyCMS в AdminModul.php в методе bootstrap прописано
```php
 if (!$app->user->isGuest && strpos($app->request->pathInfo, 'admin') === false) {
            $app->on(Application::EVENT_BEFORE_REQUEST, function () use ($app) {
                $app->getView()->on(View::EVENT_BEGIN_BODY, [$this, 'renderToolbar']);
            });
        }
```
Т.е показывай панель администратора (верхний toolbar) есть путь в адресной строке не равен 'admin'.  А у меня модуль не "admin", так же как модуль user от dektrium. Исправить это я не могу, у EasyCMS еще даже релиза нормального нет. Но у себя в проекте пока поменяла в vendor (чего делать совсем не рекомендую, но по другому пока никак). Показываю весь метод:
```php
 public function bootstrap($app)
    {
        Yii::setAlias('easyii', '@vendor/noumo/easyii');

        if ($this->showToolbar instanceof \Closure) {
            $showToolbar =  call_user_func($this->showToolbar, $app);
        } else {
            $showToolbar = $this->showToolbar;
        }

        $path = explode('/', $app->request->pathInfo);

        if (!$app->user->isGuest && in_array(array_shift($path), ['admin', 'user', 'permit']) === false && $showToolbar) {
            $app->on(Application::EVENT_BEFORE_REQUEST, function () use ($app) {
                $app->getView()->on(View::EVENT_BEGIN_BODY, [$this, 'renderToolbar']);
            });
        }
    }
```

['admin', 'user', 'permit'] - список модулей, для которых toolbar не показывать. 

В начале файла у меня таже дописано 
``  public $showToolbar = true; `` - это для того, чтобы можно по человечески передать в модуль правила, когда показывать вообще toolbar на фронте а когда нет. 
В конфиге дописала
```php
  'modules' => [
        'admin' => [
          'showToolbar' => function($app) {
              return $app->user->can('admin');
          }
        ],
]
```
Т.е у меня toolbar показывается только тогда когда у юзера есть право "admin". 

Если будет время, думаю форкну EasyCMS и допилю его, т.к у автора похоже времени совсем нет, ничего не менял почти год.

**Comment by Fedor858** [comment]
Да,автор  видимо совсем положил на проект,я кстати  давно  форкнул  его,перепилил основательно пока модули  меню и  статических  страниц.
Спасибо  за совет и  за модули.
